server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel_order_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 555913
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: localhost
    port: 6379
    password: 555913
    timeout: 30000
  mail:
    username: 948314053@qq.com
    password: tspouadpldnfbbah
    default-encoding: UTF-8
    host: smtp.qq.com



mybatis-plus:
  global-config:
    db-config:
      id-type: ASSIGN_ID

logging:
  level:
    com.fang.hotel_order_system: debug
  file:
    name: logs/log.log

